#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path


def load(path: Path) -> dict:
    return json.loads(path.read_text())


def swift_enum_case(value: str) -> str:
    if value and all(ch.isalnum() for ch in value):
        case = value[:1].lower() + value[1:]
    else:
        pieces = []
        token = ""
        for ch in value:
            if ch.isalnum():
                token += ch
            else:
                if token:
                    pieces.append(token)
                    token = ""
        if token:
            pieces.append(token)
        if not pieces:
            return "unknown"
        head = pieces[0].lower()
        tail = "".join(p[:1].upper() + p[1:] for p in pieces[1:])
        case = f"{head}{tail}"
    if case[0].isdigit():
        case = f"v{case}"
    return case


repo = Path(__file__).resolve().parents[2]
schemas = repo / "openapi" / "schemas" / "ws"
out = repo / "Sources" / "SwiftAgentHarness" / "Generated" / "WebSocketSchemaBindings.swift"
out.parent.mkdir(parents=True, exist_ok=True)

comm_resource = load(schemas / "comm-resource-topic.schema.json")
conv_event = load(schemas / "conversation-topic-event-payload.schema.json")
models_event = load(schemas / "models-registry-event-payload.schema.json")

seq_props = comm_resource.get("properties")
if seq_props is None:
    seq_props = comm_resource["oneOf"][0]["properties"]
kind_values = seq_props["kind"]["enum"]
trust_values = seq_props["trustClass"]["enum"]
origin_values = seq_props["originTrust"]["enum"]
semantic_values = conv_event["properties"]["semanticKind"]["enum"]
change_values = models_event["properties"]["changes"]["items"]["properties"]["kind"]["enum"]

def render_enum(name: str, values: list[str]) -> str:
    rows = "\n".join(
        f"    case {swift_enum_case(v)} = \"{v}\""
        for v in values
    )
    return f"public enum {name}: String, Codable, Sendable {{\n{rows}\n}}\n"


source = f"""// Generated by openapi/scripts/generate-ws-swift-bindings.py. Do not edit by hand.
import Foundation

{render_enum("WSGeneratedEnvelopeKind", kind_values)}
{render_enum("WSGeneratedTrustClass", trust_values)}
{render_enum("WSGeneratedOriginTrust", origin_values)}
{render_enum("WSGeneratedConversationSemanticKind", semantic_values)}
{render_enum("WSGeneratedModelRegistryChangeKind", change_values)}
public struct WSGeneratedConversationTopicEventPayload: Codable, Sendable {{
    public let semanticKind: WSGeneratedConversationSemanticKind
    public let jsonUTF8: String?
}}

public struct WSGeneratedConversationStatePayload: Codable, Sendable {{
    public let conversationID: UUID
    public let exists: Bool
    public let orchestration: ConversationOrchestrationState?
}}

public struct WSGeneratedConversationsRegistryPayload: Codable, Sendable {{
    public let schemaVersion: Int
    public let changes: [WSGeneratedConversationRegistryChange]
}}

public struct WSGeneratedConversationRegistryChange: Codable, Sendable {{
    public let kind: String
    public let conversationID: UUID
}}

public struct WSGeneratedModelsRegistryPayload: Codable, Sendable {{
    public let models: [Model]
    public let updatedAt: Date?
}}

public struct WSGeneratedModelsRegistryEventPayload: Codable, Sendable {{
    public let changes: [WSGeneratedModelRegistryChange]
    public let updatedAt: Date?
}}

public struct WSGeneratedModelRegistryChange: Codable, Sendable {{
    public let kind: WSGeneratedModelRegistryChangeKind
    public let modelID: UUID
    public let previous: Model?
    public let current: Model?
}}

public struct WSGeneratedCommResourceTopicEnvelope: Codable, Sendable {{
    public let kind: WSGeneratedEnvelopeKind
    public let topic: String
    public let trustClass: WSGeneratedTrustClass
    public let originTrust: WSGeneratedOriginTrust
    public let seq: Int
    public let hint: String?
    public let messageSeq: Int?
    public let checkpointSeq: Int?
    public let runId: UUID?
    public let turnOrdinal: Int?
    public let resumeToken: String?
}}
"""

out.write_text(source)
print(f"Wrote {out}")
