#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VENV="$ROOT/.openapi-bindings-venv"
PY="$VENV/bin/python"
OUT_DIR="$ROOT/openapi/generated/python"
WS_OUT_DIR="$OUT_DIR/ws"
REST_SCHEMA_TMP="$OUT_DIR/_rest_bindings.schema.json"

if [ ! -x "$PY" ]; then
  python3 -m venv "$VENV"
fi

"$PY" -m pip install --disable-pip-version-check --quiet "datamodel-code-generator==0.30.1"

rm -rf "$OUT_DIR"
mkdir -p "$WS_OUT_DIR"
mkdir -p "$OUT_DIR"

"$PY" - "$ROOT/openapi/openapi.yaml" "$REST_SCHEMA_TMP" <<'PY'
from __future__ import annotations
import json
import pathlib
import sys

import yaml

openapi_path = pathlib.Path(sys.argv[1])
out_path = pathlib.Path(sys.argv[2])
doc = yaml.safe_load(openapi_path.read_text())
schemas = doc["components"]["schemas"]
selected = [
    "StatusResponse",
    "ModelInfo",
    "ListModelsResponse",
    "QueryModelsRequest",
    "QueryModelsResponse",
    "ConversationEventsBackfillResponse",
    "ConversationSearchResponse",
    "HTTPPreconditionRequiredBody",
    "HTTPPreconditionFailedBody",
    "PreviewContextCompactionRequest",
    "ManualContextCompactionRequest",
]
def rewrite_refs(node):
    if isinstance(node, dict):
        updated = {}
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str) and value.startswith("#/components/schemas/"):
                updated[key] = value.replace("#/components/schemas/", "#/$defs/")
            else:
                updated[key] = rewrite_refs(value)
        return updated
    if isinstance(node, list):
        return [rewrite_refs(value) for value in node]
    return node

bundle = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "SileniaRESTBindings",
    "type": "object",
    "properties": {name: {"$ref": f"#/$defs/{name}"} for name in selected},
    "$defs": {name: rewrite_refs(schema) for name, schema in schemas.items()},
}
out_path.write_text(json.dumps(bundle, indent=2) + "\n")
PY

"$PY" -m datamodel_code_generator \
  --input "$REST_SCHEMA_TMP" \
  --input-file-type jsonschema \
  --output "$OUT_DIR/rest_models.py" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.11 \
  --disable-timestamp \
  --base-class pydantic.BaseModel

for schema in \
  comm-client-control.schema.json \
  comm-resource-topic.schema.json \
  conversation-topic-event-payload.schema.json \
  model-state-payload.schema.json \
  model-calls-payload.schema.json \
  models-registry-payload.schema.json \
  models-registry-event-payload.schema.json \
  conversations-registry-payload.schema.json \
  sub-agent-lifecycle-topic-payload.schema.json \
  runtime-lifecycle-event-payload.schema.json
do
  module_name="${schema%.schema.json}"
  module_name="${module_name//-/_}"
  "$PY" -m datamodel_code_generator \
    --input "$ROOT/openapi/schemas/ws/$schema" \
    --input-file-type jsonschema \
    --output "$WS_OUT_DIR/${module_name}.py" \
    --output-model-type pydantic_v2.BaseModel \
    --target-python-version 3.11 \
    --disable-timestamp \
    --base-class pydantic.BaseModel
done

cat > "$WS_OUT_DIR/__init__.py" <<'PY'
# Generated by openapi/scripts/generate-python-bindings.sh. Do not edit by hand.
PY

cat > "$OUT_DIR/__init__.py" <<'PY'
# Generated by openapi/scripts/generate-python-bindings.sh. Do not edit by hand.
from . import rest_models  # noqa: F401
from . import ws  # noqa: F401
PY

rm -f "$REST_SCHEMA_TMP"

echo "Generated Python REST/WS bindings in $OUT_DIR"
